//! JOCKY Platform Abstraction Layer
//!
//! This module deliberately provides a safe, read-only interface for
//! forensic collection. It does not perform:
//!   - direct system-call invocation
//!   - API-hook bypassing
//!   - API unhooking
//!   - process hollowing
//!   - thread hijacking
//!   - DLL injection
//!   - privilege escalation
//!   - persistence
//!   - security-product tampering
//!
//! The purpose of this layer is to keep the JOCKY execution engine
//! independent from platform-specific collection mechanisms.
//
//! Architecture:
//
//!     JOCKY IR
//!        |
//!        v
//!   Agent Dispatcher
//!        |
//!        v
//!   PlatformOps
//!      /     \
//! Windows   Linux
//!
//! Both platforms expose the same forensic abstraction.

use std::collections::BTreeMap;
use std::fmt;
use std::time::{SystemTime, UNIX_EPOCH};

/// Errors generated by the platform abstraction layer.
#[derive(Debug)]
pub enum PlatformError {
    Unsupported(&'static str),
    PermissionDenied(String),
    Io(std::io::Error),
    Parse(String),
    InvalidRequest(String),
}

impl fmt::Display for PlatformError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unsupported(msg) => write!(f, "unsupported operation: {msg}"),
            Self::PermissionDenied(msg) => write!(f, "permission denied: {msg}"),
            Self::Io(err) => write!(f, "I/O error: {err}"),
            Self::Parse(msg) => write!(f, "parse error: {msg}"),
            Self::InvalidRequest(msg) => write!(f, "invalid request: {msg}"),
        }
    }
}

impl std::error::Error for PlatformError {}

impl From<std::io::Error> for PlatformError {
    fn from(value: std::io::Error) -> Self {
        Self::Io(value)
    }
}

/// A single forensic observation.
///
/// Keeping the result structured rather than returning arbitrary strings
/// makes the output suitable for the JOCKY evidence ledger.
#[derive(Debug, Clone)]
pub struct Observation {
    pub artifact: String,
    pub timestamp_unix_ms: u128,
    pub fields: BTreeMap<String, String>,
}

impl Observation {
    pub fn new<S: Into<String>>(artifact: S) -> Self {
        Self {
            artifact: artifact.into(),
            timestamp_unix_ms: current_time_ms(),
            fields: BTreeMap::new(),
        }
    }

    pub fn with_field<K, V>(mut self, key: K, value: V) -> Self
    where
        K: Into<String>,
        V: Into<String>,
    {
        self.fields.insert(key.into(), value.into());
        self
    }
}

/// Result returned by a collector.
///
/// `observations` contains normalized forensic records.
/// `warnings` contains non-fatal collection problems.
#[derive(Debug, Clone)]
pub struct CollectionResult {
    pub artifact: String,
    pub observations: Vec<Observation>,
    pub warnings: Vec<String>,
}

impl CollectionResult {
    pub fn empty<S: Into<String>>(artifact: S) -> Self {
        Self {
            artifact: artifact.into(),
            observations: Vec::new(),
            warnings: Vec::new(),
        }
    }
}

/// Normalized platform information.
#[derive(Debug, Clone)]
pub struct SystemInformation {
    pub operating_system: String,
    pub architecture: String,
    pub hostname: String,
    pub process_id: u32,
}

/// The platform-neutral forensic interface.
///
/// `main.rs` and the IR executor should depend on this trait rather than
/// knowing whether the agent is running on Windows or Linux.
pub trait PlatformOps {
    /// Return basic host information.
    fn system_information(&self) -> Result<SystemInformation, PlatformError>;

    /// Collect running-process metadata.
    ///
    /// This is metadata collection only; no process is opened for code
    /// injection, modification, suspension, or execution.
    fn collect_processes(&self) -> Result<CollectionResult, PlatformError>;

    /// Collect network-connection metadata.
    fn collect_network_connections(&self) -> Result<CollectionResult, PlatformError>;

    /// Collect logged-in users where supported.
    fn collect_users(&self) -> Result<CollectionResult, PlatformError>;

    /// Collect service metadata where supported.
    fn collect_services(&self) -> Result<CollectionResult, PlatformError>;

    /// Collect startup-item metadata where supported.
    fn collect_startup_items(&self) -> Result<CollectionResult, PlatformError>;

    /// Collect file metadata for an explicitly supplied path.
    ///
    /// This function intentionally does not execute or modify the target.
    fn collect_file_metadata(
        &self,
        path: &str,
    ) -> Result<CollectionResult, PlatformError>;

    /// Dispatch a normalized JOCKY artifact name.
    fn collect(&self, artifact: &str) -> Result<CollectionResult, PlatformError> {
        match artifact {
            "processes" => self.collect_processes(),

            "network_connections" => {
                self.collect_network_connections()
            }

            "users" => self.collect_users(),

            "services" => self.collect_services(),

            "startup_items" => self.collect_startup_items(),

            "system_information" => {
                let info = self.system_information()?;

                let observation = Observation::new("system_information")
                    .with_field("operating_system", info.operating_system)
                    .with_field("architecture", info.architecture)
                    .with_field("hostname", info.hostname)
                    .with_field("process_id", info.process_id.to_string());

                Ok(CollectionResult {
                    artifact: "system_information".to_string(),
                    observations: vec![observation],
                    warnings: Vec::new(),
                })
            }

            "file_metadata" => Err(PlatformError::InvalidRequest(
                "file_metadata requires an explicit path; \
                 use collect_file_metadata()"
                    .to_string(),
            )),

            "authentication_events" => {
                Err(PlatformError::Unsupported(
                    "authentication_events is not implemented \
                     by the generic platform layer",
                ))
            }

            other => Err(PlatformError::InvalidRequest(format!(
                "unknown JOCKY artifact: {other}"
            ))),
        }
    }
}

/// Return the current Unix timestamp in milliseconds.
pub fn current_time_ms() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
}

/// Return the current process ID.
pub fn current_process_id() -> u32 {
    std::process::id()
}

/// Return a normalized platform identifier.
///
/// These values correspond to the platform names used by the JOCKY IR.
pub fn current_platform() -> &'static str {
    if cfg!(target_os = "windows") {
        "windows"
    } else if cfg!(target_os = "linux") {
        "linux"
    } else if cfg!(target_os = "macos") {
        "macos"
    } else {
        "unknown"
    }
}

/// Return the target architecture.
pub fn current_architecture() -> &'static str {
    std::env::consts::ARCH
}

/// Return the current hostname.
///
/// Failure is converted into a stable fallback rather than terminating
/// the complete forensic collection pipeline.
pub fn hostname() -> String {
    std::env::var("COMPUTERNAME")
        .or_else(|_| std::env::var("HOSTNAME"))
        .unwrap_or_else(|_| "unknown".to_string())
}

// ----------------------------------------------------------------------
// Windows implementation
// ----------------------------------------------------------------------

#[cfg(target_os = "windows")]
pub mod windows {
    use super::*;
    use std::process::Command;
    use sysinfo::System;

    #[derive(Debug, Default, Clone)]
    pub struct WindowsPlatform;

    impl WindowsPlatform {
        pub fn new() -> Self {
            Self
        }
    }

    impl PlatformOps for WindowsPlatform {
        fn system_information(&self) -> Result<SystemInformation, PlatformError> {
            Ok(SystemInformation {
                operating_system: "windows".to_string(),
                architecture: current_architecture().to_string(),
                hostname: hostname(),
                process_id: current_process_id(),
            })
        }

        fn collect_processes(&self) -> Result<CollectionResult, PlatformError> {
            let mut result = CollectionResult::empty("processes");
            let mut sys = System::new_all();
            sys.refresh_processes();

            for (pid, process) in sys.processes() {
                let exe_path = process.exe()
                    .map(|p| p.to_string_lossy().to_string())
                    .unwrap_or_else(|| "unknown".to_string());

                let obs = Observation::new("processes")
                    .with_field("pid", pid.as_u32().to_string())
                    .with_field("name", process.name().to_string()) // FIXED: removed to_string_lossy()
                    .with_field("exe_path", exe_path)
                    .with_field("memory_kb", (process.memory() / 1024).to_string());
                
                result.observations.push(obs);
            }
            Ok(result)
        }

        fn collect_network_connections(&self) -> Result<CollectionResult, PlatformError> {
            let mut result = CollectionResult::empty("network_connections");

            // Living-off-the-Land: Use native netstat to avoid hooking network APIs
            if let Ok(output) = Command::new("netstat").args(&["-ano"]).output() {
                let stdout = String::from_utf8_lossy(&output.stdout);

                for line in stdout.lines().skip(4) {
                    let parts: Vec<&str> = line.split_whitespace().collect();
                    if parts.len() >= 4 {
                        let protocol = parts[0];
                        let local_address = parts[1];
                        let remote_address = parts[2];
                        
                        let state = if parts.len() == 5 { parts[3] } else { "LISTENING" };
                        let pid = if parts.len() == 5 { parts[4] } else { parts[3] };

                        let obs = Observation::new("network_connections")
                            .with_field("protocol", protocol.to_string())
                            .with_field("local_address", local_address.to_string())
                            .with_field("remote_address", remote_address.to_string())
                            .with_field("state", state.to_string())
                            .with_field("pid", pid.to_string());
                        
                        result.observations.push(obs);
                    }
                }
            } else {
                result.warnings.push("Failed to execute netstat utility".to_string());
            }
            Ok(result)
        }

        fn collect_users(&self) -> Result<CollectionResult, PlatformError> {
            let mut result = CollectionResult::empty("users");

            if let Ok(output) = Command::new("net").arg("user").output() {
                let stdout = String::from_utf8_lossy(&output.stdout);
                for line in stdout.lines() {
                    if line.starts_with("---") || line.contains("User accounts") || line.contains("command completed") {
                        continue;
                    }
                    for username in line.split_whitespace() {
                        let obs = Observation::new("users")
                            .with_field("username", username.to_string())
                            .with_field("enabled", "true".to_string());
                        result.observations.push(obs);
                    }
                }
            }
            Ok(result)
        }

        fn collect_services(&self) -> Result<CollectionResult, PlatformError> {
            let mut result = CollectionResult::empty("services");

            if let Ok(output) = Command::new("sc").arg("query").output() {
                let stdout = String::from_utf8_lossy(&output.stdout);
                let mut current_name = String::new();

                for line in stdout.lines() {
                    let trimmed = line.trim();
                    if trimmed.starts_with("SERVICE_NAME:") {
                        current_name = trimmed.replace("SERVICE_NAME:", "").trim().to_string();
                    }
                    if trimmed.starts_with("STATE") {
                        let obs = Observation::new("services")
                            .with_field("name", current_name.clone())
                            .with_field("status", trimmed.to_string());
                        result.observations.push(obs);
                    }
                }
            }
            Ok(result)
        }

        fn collect_startup_items(&self) -> Result<CollectionResult, PlatformError> {
            let mut result = CollectionResult::empty("startup_items");
            // Standard simulated registry pull for SIH prototype
            result.observations.push(Observation::new("startup_items")
                .with_field("name", "HKLM Run".to_string())
                .with_field("path", r"HKLM\Software\Microsoft\Windows\CurrentVersion\Run".to_string()));
            Ok(result)
        }

        fn collect_file_metadata(&self, path: &str) -> Result<CollectionResult, PlatformError> {
            collect_standard_file_metadata(path)
        }
    }
}

// ----------------------------------------------------------------------
// Linux implementation
// ----------------------------------------------------------------------

#[cfg(target_os = "linux")]
pub mod linux {
    use super::*;

    /// Linux implementation of the safe platform abstraction.
    #[derive(Debug, Default, Clone, Copy)]
    pub struct LinuxPlatform;

    impl LinuxPlatform {
        pub fn new() -> Self {
            Self
        }
    }

    impl PlatformOps for LinuxPlatform {
        fn system_information(
            &self,
        ) -> Result<SystemInformation, PlatformError> {
            Ok(SystemInformation {
                operating_system: "linux".to_string(),
                architecture: current_architecture().to_string(),
                hostname: hostname(),
                process_id: current_process_id(),
            })
        }

        fn collect_processes(
            &self,
        ) -> Result<CollectionResult, PlatformError> {
            let mut result = CollectionResult::empty("processes");

            let proc_dir = std::path::Path::new("/proc");

            if !proc_dir.exists() {
                return Err(PlatformError::Unsupported(
                    "/proc is unavailable",
                ));
            }

            for entry in std::fs::read_dir(proc_dir)? {
                let entry = match entry {
                    Ok(value) => value,
                    Err(err) => {
                        result.warnings.push(err.to_string());
                        continue;
                    }
                };

                let file_name = entry.file_name();

                let pid_text = file_name.to_string_lossy();

                if !pid_text.chars().all(|c| c.is_ascii_digit()) {
                    continue;
                }

                let pid = pid_text.clone();

                let status_path =
                    entry.path().join("status");

                let mut observation =
                    Observation::new("processes")
                        .with_field("pid", pid.to_string());

                match std::fs::read_to_string(&status_path) {
                    Ok(status) => {
                        for line in status.lines() {
                            if let Some(name) =
                                line.strip_prefix("Name:")
                            {
                                observation = observation
                                    .with_field(
                                        "name",
                                        name.trim(),
                                    );
                            }

                            if let Some(state) =
                                line.strip_prefix("State:")
                            {
                                observation = observation
                                    .with_field(
                                        "state",
                                        state.trim(),
                                    );
                            }

                            if let Some(uid) =
                                line.strip_prefix("Uid:")
                            {
                                observation = observation
                                    .with_field(
                                        "uid",
                                        uid.trim(),
                                    );
                            }
                        }
                    }

                    Err(err) => {
                        result.warnings.push(format!(
                            "cannot read {}: {}",
                            status_path.display(),
                            err
                        ));
                    }
                }

                result.observations.push(observation);
            }

            Ok(result)
        }

        fn collect_network_connections(
            &self,
        ) -> Result<CollectionResult, PlatformError> {
            let mut result =
                CollectionResult::empty("network_connections");

            collect_proc_network_file(
                "/proc/net/tcp",
                "tcp",
                &mut result,
            )?;

            collect_proc_network_file(
                "/proc/net/udp",
                "udp",
                &mut result,
            )?;

            collect_proc_network_file(
                "/proc/net/tcp6",
                "tcp6",
                &mut result,
            )?;

            collect_proc_network_file(
                "/proc/net/udp6",
                "udp6",
                &mut result,
            )?;

            Ok(result)
        }

        fn collect_users(
            &self,
        ) -> Result<CollectionResult, PlatformError> {
            let mut result = CollectionResult::empty("users");

            let passwd = std::fs::read_to_string("/etc/passwd")?;

            for line in passwd.lines() {
                if line.trim().is_empty()
                    || line.starts_with('#')
                {
                    continue;
                }

                let fields: Vec<&str> =
                    line.split(':').collect();

                if fields.len() < 7 {
                    continue;
                }

                let observation =
                    Observation::new("users")
                        .with_field("username", fields[0])
                        .with_field("uid", fields[2])
                        .with_field("gid", fields[3])
                        .with_field("home", fields[5])
                        .with_field("shell", fields[6]);

                result.observations.push(observation);
            }

            Ok(result)
        }

        fn collect_services(
            &self,
        ) -> Result<CollectionResult, PlatformError> {
            let mut result = CollectionResult::empty("services");

            //
            // Read-only systemd inspection.
            //
            // We deliberately do not enable/disable/start/stop services.
            //
            let systemd_path =
                std::path::Path::new("/etc/systemd/system");

            if systemd_path.exists() {
                for entry in std::fs::read_dir(systemd_path)? {
                    let entry = match entry {
                        Ok(value) => value,
                        Err(err) => {
                            result.warnings.push(err.to_string());
                            continue;
                        }
                    };

                    let path = entry.path();

                    if path.is_file() {
                        let name = path
                            .file_name()
                            .map(|x| x.to_string_lossy().to_string())
                            .unwrap_or_default();

                        result.observations.push(
                            Observation::new("services")
                                .with_field("name", name)
                                .with_field(
                                    "path",
                                    path.display().to_string(),
                                ),
                        );
                    }
                }
            } else {
                result.warnings.push(
                    "/etc/systemd/system is unavailable"
                        .to_string(),
                );
            }

            Ok(result)
        }

        fn collect_startup_items(
            &self,
        ) -> Result<CollectionResult, PlatformError> {
            let mut result =
                CollectionResult::empty("startup_items");

            let locations = [
                "/etc/rc.local",
                "/etc/profile",
                "/etc/profile.d",
            ];

            for location in locations {
                let path =
                    std::path::Path::new(location);

                if !path.exists() {
                    continue;
                }

                let observation =
                    Observation::new("startup_items")
                        .with_field(
                            "path",
                            path.display().to_string(),
                        )
                        .with_field(
                            "type",
                            if path.is_dir() {
                                "directory"
                            } else {
                                "file"
                            },
                        );

                result.observations.push(observation);
            }

            Ok(result)
        }

        fn collect_file_metadata(
            &self,
            path: &str,
        ) -> Result<CollectionResult, PlatformError> {
            collect_standard_file_metadata(path)
        }
    }
}


// ----------------------------------------------------------------------
// Generic file metadata collector
// ----------------------------------------------------------------------

/// Collect metadata without reading/executing the file contents.
///
/// This is useful for a JOCKY IR operation such as:
///
///     collect file_metadata
///
/// when the agent has received an explicitly authorized path.
pub fn collect_standard_file_metadata(
    path: &str,
) -> Result<CollectionResult, PlatformError> {
    use std::path::Path;

    let target = Path::new(path);

    let metadata = std::fs::symlink_metadata(target)
        .map_err(|err| {
            if err.kind() == std::io::ErrorKind::PermissionDenied {
                PlatformError::PermissionDenied(
                    path.to_string(),
                )
            } else {
                PlatformError::Io(err)
            }
        })?;

    let file_type = metadata.file_type();

    let mut observation =
        Observation::new("file_metadata")
            .with_field(
                "path",
                target.display().to_string(),
            )
            .with_field(
                "is_file",
                file_type.is_file().to_string(),
            )
            .with_field(
                "is_directory",
                file_type.is_dir().to_string(),
            )
            .with_field(
                "is_symlink",
                file_type.is_symlink().to_string(),
            )
            .with_field(
                "size",
                metadata.len().to_string(),
            );

    if let Ok(created) = metadata.created() {
        if let Ok(duration) =
            created.duration_since(UNIX_EPOCH)
        {
            observation = observation.with_field(
                "created_unix_ms",
                duration.as_millis().to_string(),
            );
        }
    }

    if let Ok(modified) = metadata.modified() {
        if let Ok(duration) =
            modified.duration_since(UNIX_EPOCH)
        {
            observation = observation.with_field(
                "modified_unix_ms",
                duration.as_millis().to_string(),
            );
        }
    }

    Ok(CollectionResult {
        artifact: "file_metadata".to_string(),
        observations: vec![observation],
        warnings: Vec::new(),
    })
}


// ----------------------------------------------------------------------
// Linux /proc helpers
// ----------------------------------------------------------------------

#[cfg(target_os = "linux")]
fn collect_proc_network_file(
    path: &str,
    protocol: &str,
    result: &mut CollectionResult,
) -> Result<(), PlatformError> {
    let content = match std::fs::read_to_string(path) {
        Ok(value) => value,
        Err(err) => {
            result.warnings.push(format!(
                "cannot read {}: {}",
                path, err
            ));

            return Ok(());
        }
    };

    for line in content.lines().skip(1) {
        let fields: Vec<&str> =
            line.split_whitespace().collect();

        if fields.len() < 4 {
            continue;
        }

        let local_address = fields[1];
        let remote_address = fields[2];
        let state = fields[3];

        let observation =
            Observation::new("network_connections")
                .with_field("protocol", protocol)
                .with_field(
                    "local_address",
                    local_address,
                )
                .with_field(
                    "remote_address",
                    remote_address,
                )
                .with_field("state", state);

        result.observations.push(observation);
    }

    Ok(())
}


// ----------------------------------------------------------------------
// Platform factory
// ----------------------------------------------------------------------

/// Return the platform implementation used by the agent.
///
/// This function keeps `main.rs` platform-neutral.
#[cfg(target_os = "windows")]
pub fn platform() -> Box<dyn PlatformOps> {
    Box::new(windows::WindowsPlatform::new())
}

#[cfg(target_os = "linux")]
pub fn platform() -> Box<dyn PlatformOps> {
    Box::new(linux::LinuxPlatform::new())
}

#[cfg(not(any(target_os = "windows", target_os = "linux")))]
pub fn platform() -> Box<dyn PlatformOps> {
    Box::new(UnsupportedPlatform)
}


// ----------------------------------------------------------------------
// Unsupported-platform fallback
// ----------------------------------------------------------------------

#[derive(Debug, Default, Clone, Copy)]
pub struct UnsupportedPlatform;

impl PlatformOps for UnsupportedPlatform {
    fn system_information(
        &self,
    ) -> Result<SystemInformation, PlatformError> {
        Ok(SystemInformation {
            operating_system:
                std::env::consts::OS.to_string(),
            architecture:
                current_architecture().to_string(),
            hostname: hostname(),
            process_id: current_process_id(),
        })
    }

    fn collect_processes(
        &self,
    ) -> Result<CollectionResult, PlatformError> {
        Err(PlatformError::Unsupported(
            "process collection",
        ))
    }

    fn collect_network_connections(
        &self,
    ) -> Result<CollectionResult, PlatformError> {
        Err(PlatformError::Unsupported(
            "network collection",
        ))
    }

    fn collect_users(
        &self,
    ) -> Result<CollectionResult, PlatformError> {
        Err(PlatformError::Unsupported(
            "user collection",
        ))
    }

    fn collect_services(
        &self,
    ) -> Result<CollectionResult, PlatformError> {
        Err(PlatformError::Unsupported(
            "service collection",
        ))
    }

    fn collect_startup_items(
        &self,
    ) -> Result<CollectionResult, PlatformError> {
        Err(PlatformError::Unsupported(
            "startup collection",
        ))
    }

    fn collect_file_metadata(
        &self,
        path: &str,
    ) -> Result<CollectionResult, PlatformError> {
        collect_standard_file_metadata(path)
    }
}


// ----------------------------------------------------------------------
// Tests
// ----------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn timestamp_is_nonzero() {
        assert!(current_time_ms() > 0);
    }

    #[test]
    fn platform_is_known() {
        let platform = current_platform();

        assert!(
            platform == "windows"
                || platform == "linux"
                || platform == "macos"
                || platform == "unknown"
        );
    }

    #[test]
    fn architecture_is_nonempty() {
        assert!(!current_architecture().is_empty());
    }

    #[test]
    fn observation_fields_work() {
        let item = Observation::new("test")
            .with_field("name", "jocky")
            .with_field("version", "0.3");

        assert_eq!(
            item.fields.get("name"),
            Some(&"jocky".to_string())
        );

        assert_eq!(
            item.fields.get("version"),
            Some(&"0.3".to_string())
        );
    }

    #[test]
    fn unsupported_artifact_returns_error() {
        let agent = platform();

        let result = agent.collect("does_not_exist");

        assert!(result.is_err());
    }

    #[test]
    fn system_information_is_available() {
        let agent = platform();

        let result = agent.system_information();

        assert!(result.is_ok());

        let info = result.unwrap();

        assert!(!info.operating_system.is_empty());
        assert!(!info.architecture.is_empty());
    }
}